swagger: "2.0"
info:
  x-ibm-name: loopback
  title: loopback
  version: 1.0.0
schemes:
- https
basePath: /loopback
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  client_id:
    description: ""
    in: header
    name: X-IBM-Client-Id
    type: apiKey
  oauth:
    description: ""
    flow: application
    scopes:
      scope1: ""
    tokenUrl: https://$(catalog.url)/test/oauth2/token
    type: oauth2
    x-ibm-oauth-provider: test-client-oauth-provider-1-0-0-ebf1
    x-scopeValidate:
      tls-profile: ""
      url: ""
    x-ibm-comment:
    - 'OA201: Found OAuth2 security definition using the provider name://../oauth-providers/test-client-oauth-provider-1-0-0-ebf1.yml.  The
      corresponding OAuth provider for type API Gateway must exist on the server.
      name://../oauth-providers/test-client-oauth-provider-1-0-0-ebf1.yml'
security:
- oauth:
  - scope1
  client_id: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - set-variable:
        actions:
        - set: message.body
          value: '{"test":"loopback"}'
          type: string
        title: set-variable
        version: 2.0.0
        comment:
        - 'SV01: Found `set-variable` policy and converted to API Gateway `set-variable`
          policy.'
        - 'SV06: Required property `type` not found. Added `type` of `string` to conform
          to the API Gateway specification, and it is consistent with the provided
          `value`. For details, see: https://www.ibm.com/docs/en/api-connect/10.0.x?topic=cadag-messages-generated-during-conversion-apis-datapower-api-gateway#SETVARIABLE_TYPE_ADDED'
  phase: realized
  gateway: datapower-api-gateway
  type: rest
  compatibility:
    enforce-required-params: false
    comment:
    - 'API44: Set compatibility toggle `enforce-required-params` to value: `false`.
      For details, see: https://www.ibm.com/docs/en/api-connect/10.0.x?topic=cadag-messages-generated-during-conversion-apis-datapower-api-gateway#SET_COMPATIBILITY_TOGGLE'
    - 'API44: Set compatibility toggle `request-headers` to value: `true`. For details,
      see: https://www.ibm.com/docs/en/api-connect/10.0.x?topic=cadag-messages-generated-during-conversion-apis-datapower-api-gateway#SET_COMPATIBILITY_TOGGLE'
    - 'API43: Created `compatibility:` section for API-wide toggles set by migration
      utility. For details, see: https://www.ibm.com/docs/en/api-connect/10.0.x?topic=cadag-messages-generated-during-conversion-apis-datapower-api-gateway#COMPATIBILITY_INFO'
    request-headers: true
    migrated-api: true
  buffering: true
paths:
  /:
    get:
      responses:
        "200":
          description: 200 OK
      security:
      - client_id: []
        oauth:
        - scope1
definitions: {}
tags: []
x-ibm-comment:
- 'AMU version used to port this API: v10.0.3.0-R4-7918d8722ed80dff79ad214746a67cd59418c6e7-2021-12-15T21:36:45Z'
- 'API03: Suffix  appended to API `title` and `x-ibm-name`. For details, see: https://www.ibm.com/docs/en/api-connect/10.0.x?topic=cadag-messages-generated-during-conversion-apis-datapower-api-gateway#API_NAME_ADDED_SUFFIX'
- 'API06: Changed gateway type to `datapower-api-gateway`.'
- 'API14: Ported v5-compatible policies to work with the API Gateway and updated policy
  versions.'
- 'API45: Compatibility toggle: `allow-chunked-uploads` set to value: `false`, which
  is the same as the API Gateway default. For details, see: https://www.ibm.com/docs/en/api-connect/10.0.x?topic=cadag-messages-generated-during-conversion-apis-datapower-api-gateway#COMPAT_TOGGLE_MATCHES_APIGW_DEFAULT'
- 'API45: Compatibility toggle: `copy-id-headers-to-message` set to value: `false`,
  which is the same as the API Gateway default. For details, see: https://www.ibm.com/docs/en/api-connect/10.0.x?topic=cadag-messages-generated-during-conversion-apis-datapower-api-gateway#COMPAT_TOGGLE_MATCHES_APIGW_DEFAULT'
- 'API45: Compatibility toggle: `return-v5-responses` set to value: `false`, which
  is the same as the API Gateway default. For details, see: https://www.ibm.com/docs/en/api-connect/10.0.x?topic=cadag-messages-generated-during-conversion-apis-datapower-api-gateway#COMPAT_TOGGLE_MATCHES_APIGW_DEFAULT'
- 'API61: Set buffering property to true. For details, see: https://www.ibm.com/docs/en/api-connect/10.0.x?topic=cadag-messages-generated-during-conversion-apis-datapower-api-gateway#SET_BUFFERING'
- 'API24: Removed redundant `parse` policy from the beginning of the assembly. For
  details, see: https://www.ibm.com/docs/en/api-connect/10.0.x?topic=cadag-messages-generated-during-conversion-apis-datapower-api-gateway#REMOVED_REDUNDANT_FRONT_PARSE'
